### ISSUE TITLE
"Feature" suggestion: auto-opening http://localhost:<port>

### ISSUE THREAD

**Issue by liar666** [Norconex/jef#3]
At least in Linux, thus in the "jef-monitor.sh" file you could add something like:
gnome-open 'http://localhost:<configured_port>"
(or exo-open/xdg-open/gvfs-open/kde-open according to the detected desktop environment)
So that the GUI is automagically opened

[Just thinking out loud:]
However, since JEF might run on another machine that the one where the GUI is opened, there might be a configurable option to enable/disable such a behaviour
Or maybe that line (xxx-open '"localhost"...) could just be printed on the commandline?

**Comment by essiembre** [comment]
Thanks for the suggestion, but given this is a web app (not meant as a desktop app) and since it is often launched remotely (sometimes on servers with no GUI), it will not be added in.  

You should easily be able to modify the startup script to add this to your own installation, using your favorite launch command.

**Comment by essiembre** [comment]
FYI, I have added a logging line on startup that states the URL to open in your browser.  Available in [latest snapshot](https://www.norconex.com/jef/monitor/download).
